### ISSUE TITLE
"Unable to leave session" error

### ISSUE THREAD

**Issue by Kickero** [Playabl-io/playabl#254] opened 2024-02-18 02:57 UTC
**Describe the bug**
Attempting to leave a session returns an error. 

**To Reproduce**

1. Go to a joined session. 
2. Click "leave session." 

**Expected behavior**

**Screenshots**
![image](https://github.com/Playabl-io/playabl/assets/50270118/6ce24521-ad58-435b-a4d7-a2ec0bdf0111)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Chrome (Version 121.0.6167.185) 

**Smartphone (please complete the following information):**

- Device: iPhone SE
- OS: iOS 17.3.1
- Browser: Safari

**Additional context**
This error was encountered in this game: https://app.playabl.io/games/439/overview. Not replicated in other games so far.

**Comment by jongrim** [comment] 2024-02-22 06:56
Thanks for reporting! Is the issue ongoing? Can you tell me which user is getting the error? Do you see any errors in [the browser console](https://balsamiq.com/support/faqs/browserconsole)?

**Comment by Kickero** [comment] 2024-02-25 03:26
Yes, here is the error that's returned in the browser console: 

index-7c7fe5c3.js:245 
 DELETE https://app.playabl.io/.netlify/functions/processRsvp?sessionId=1397&userId=614047b3-7b7f-4657-a137-450dfda07c78 502 (Bad Gateway)

**Comment by jongrim** [comment] 2024-02-27 15:58
Okay, I have a rough idea of the issue, but don't have a permanent fix yet. I believe the issue is the use of double quotes in the game title. I see errors in the function logs where the string "Sal" is somehow getting grabbed and used as JSON. It must be that the double quote is terminating a string or something. I think if you change the game title to single quotes it will allow the player to remove themself. Aside from that, I'll work on making the system more robust so that the title can't break the function, because you really shouldn't have to worry about this.

**Comment by jongrim** [comment] 2024-03-25 06:35
Closing since some time has passed. Feel free to reopen if the issue is observed again.

**Closed by jongrim** 2024-03-25 06:35 UTC
Labels: bug
